/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coupon {
  'expiryTimestamp' : bigint,
  'discountValue' : bigint,
  'code' : string,
  'discountType' : string,
  'usedCount' : bigint,
  'usageLimit' : bigint,
}
export interface Session {
  'age' : string,
  'finalPrice' : bigint,
  'status' : string,
  'duration' : bigint,
  'couponUsed' : string,
  'listenerAssigned' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'userPhone' : string,
  'language' : string,
  'freeMinutesUsed' : bigint,
  'gender' : string,
  'sessionId' : string,
  'dateCode' : string,
  'preferredListener' : string,
  'problemCategory' : string,
}
export interface User {
  'referralCode' : string,
  'totalReferrals' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'freeMinutesBalance' : bigint,
  'referredBy' : string,
  'phone' : string,
}
export interface _SERVICE {
  'addCoupon' : ActorMethod<[string, string, bigint, bigint, bigint], boolean>,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'assignListener' : ActorMethod<[string, string], boolean>,
  'getCoupons' : ActorMethod<[], Array<Coupon>>,
  'getSessions' : ActorMethod<[string], Array<Session>>,
  'getUserByPhone' : ActorMethod<[string], [] | [User]>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'submitSession' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
    ],
    { 'userReferralCode' : string, 'sessionId' : string }
  >,
  'updateSessionStatus' : ActorMethod<[string, string], boolean>,
  'validateCoupon' : ActorMethod<
    [string, bigint],
    {
      'discountValue' : bigint,
      'valid' : boolean,
      'discountType' : string,
      'message' : string,
    }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];