/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Coupon = IDL.Record({
  'expiryTimestamp' : IDL.Int,
  'discountValue' : IDL.Nat,
  'code' : IDL.Text,
  'discountType' : IDL.Text,
  'usedCount' : IDL.Nat,
  'usageLimit' : IDL.Nat,
});
export const Session = IDL.Record({
  'age' : IDL.Text,
  'finalPrice' : IDL.Nat,
  'status' : IDL.Text,
  'duration' : IDL.Nat,
  'couponUsed' : IDL.Text,
  'listenerAssigned' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'userPhone' : IDL.Text,
  'language' : IDL.Text,
  'freeMinutesUsed' : IDL.Nat,
  'gender' : IDL.Text,
  'sessionId' : IDL.Text,
  'dateCode' : IDL.Text,
  'preferredListener' : IDL.Text,
  'problemCategory' : IDL.Text,
});
export const User = IDL.Record({
  'referralCode' : IDL.Text,
  'totalReferrals' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'freeMinutesBalance' : IDL.Nat,
  'referredBy' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCoupon' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Int, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignListener' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getSessions' : IDL.Func([IDL.Text], [IDL.Vec(Session)], ['query']),
  'getUserByPhone' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'submitSession' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Record({ 'userReferralCode' : IDL.Text, 'sessionId' : IDL.Text })],
      [],
    ),
  'updateSessionStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'validateCoupon' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [
        IDL.Record({
          'discountValue' : IDL.Nat,
          'valid' : IDL.Bool,
          'discountType' : IDL.Text,
          'message' : IDL.Text,
        }),
      ],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Coupon = IDL.Record({
    'expiryTimestamp' : IDL.Int,
    'discountValue' : IDL.Nat,
    'code' : IDL.Text,
    'discountType' : IDL.Text,
    'usedCount' : IDL.Nat,
    'usageLimit' : IDL.Nat,
  });
  const Session = IDL.Record({
    'age' : IDL.Text,
    'finalPrice' : IDL.Nat,
    'status' : IDL.Text,
    'duration' : IDL.Nat,
    'couponUsed' : IDL.Text,
    'listenerAssigned' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'userPhone' : IDL.Text,
    'language' : IDL.Text,
    'freeMinutesUsed' : IDL.Nat,
    'gender' : IDL.Text,
    'sessionId' : IDL.Text,
    'dateCode' : IDL.Text,
    'preferredListener' : IDL.Text,
    'problemCategory' : IDL.Text,
  });
  const User = IDL.Record({
    'referralCode' : IDL.Text,
    'totalReferrals' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'freeMinutesBalance' : IDL.Nat,
    'referredBy' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addCoupon' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Int, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'assignListener' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getSessions' : IDL.Func([IDL.Text], [IDL.Vec(Session)], ['query']),
    'getUserByPhone' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'submitSession' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Record({ 'userReferralCode' : IDL.Text, 'sessionId' : IDL.Text })],
        [],
      ),
    'updateSessionStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'validateCoupon' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [
          IDL.Record({
            'discountValue' : IDL.Nat,
            'valid' : IDL.Bool,
            'discountType' : IDL.Text,
            'message' : IDL.Text,
          }),
        ],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };